version: '3'
services:
  postgres:
    image: postgres
    volumes:
      - {$PWD}/db/data:/var/lib/postgresql/data
  rails:
    build: .
    command: bundle exec rails s -p 5000 -b '0.0.0.0'
    volumes:
      - .:/mnt/rails
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    links:
      - postgres